src/app.scss, src/lib/Chat.svelte
Fixed a couple of small bugs with the chat rename new functionality
=> Chat rename bugfix

src/app.scss, src/lib/Chat.svelte
=> Chat-like conversation, all right-aligned

src/lib/Chat.svelte
=> added option to delete individual chat

src/lib/Export.svelte, src/lib/Sidebar.svelte
add a new function: export messages as markdown
=> add a new function: export messages as markdown

package-lock.json, package.json, src/app.scss, src/lib/Chat.svelte, src/lib/Code.svelte
I added a new function that can copy the code in the code block.
=> add copy function

Dockerfile, README.md, docker-compose.yml, package.json
Add docker usage for easy deployment
=> Support using with docker compose

package-lock.json, package.json, src/app.scss, src/lib/Sidebar.svelte, src/lib/Storage.svelte
Add a small X button that delete the individual chat / conversation. Visible only when hovering over the chat (conversation).
If the uses tries to delete the active conversation will switch to a different conversation first. 
Does not allow deleting the last conversation.
=> Delete individual chat functionality

src/lib/Chat.svelte
preselect text since you want to change the text.
=> preselect text in the Rename chat modal.

src/lib/Chat.svelte
Doesn't send max_tokens to API if request prompt tokens + requested max_tokens > model's max tokens
=> Fix token limit issue in #161

src/lib/Chat.svelte, src/lib/ChatCompletionResponse.svelte, src/lib/ChatRequest.svelte, src/lib/ChatSettingField.svelte, src/lib/ChatSettingsModal.svelte, src/lib/EditMessage.svelte, src/lib/Profiles.svelte, src/lib/Settings.svelte, src/lib/Stats.svelte, src/lib/Storage.svelte, src/lib/Types.svelte, src/lib/Util.svelte
A refactor of sendRequest.  Hopefully fixes more bugs and edge case issues than it introduces.
=> Refactor sendRequest

src/lib/ImageStore.svelte, src/lib/Models.svelte, src/lib/Storage.svelte
- Pricing on GPT-3.5 wasn't clear in the original announcement, but it appears all 3.5-turbo 4k is now 0.0015 for input.
- Deleting messages with images could leave the image in indexedDB in some cases.
=> Update pricing again, fix memory leak in image support

src/lib/Chat.svelte, src/lib/Messages.svelte
- Removal of key seemed to work at first, but messages would get mixed up after summarization, message deletion, etc.
=> Fix issue with messages getting mixed up

src/lib/ChatRequest.svelte, src/lib/EditMessage.svelte, src/lib/Settings.svelte, src/lib/Storage.svelte, src/lib/Types.svelte
- Fix message edits not being saved to chatStore regression
- Some other changes, like adding ability to adjust temperature of summary request.
=> Fix message edits not being saved to chatStore, a few other tweaks

src/app.scss, src/lib/ChatCompletionResponse.svelte, src/lib/ChatRequest.svelte, src/lib/Storage.svelte
- Fixed what was blocking the sticky tool drawer, RE #205
- Try to track down intermittent issue where a streaming response will get stuck to the point where you need to refresh the page to continue. Not sure it's fixed.
=> Sticky tool drawer, try to track down streaming responses getting stuck

src/lib/Models.svelte
=> Fix disabled OpenAI models #243

src/lib/ChatRequest.svelte
Fix rounding issue in token counts
=> Fix rounding issue in token counts

src/lib/ChatRequest.svelte, src/lib/ChatSettingsModal.svelte, src/lib/EditMessage.svelte, src/lib/NewChat.svelte, src/lib/Profiles.svelte, src/lib/Settings.svelte, src/lib/Types.svelte, src/lib/Util.svelte, src/lib/providers/openai/models.svelte, src/lib/providers/petals/request.svelte
- Allow the WebSocket connection to petals be held open, sending/receiving deltas for faster processing. (Modifying messages, using hidden prompt prefixes, etc., will for a new WebSocket for every request, making them much slower.)
- Updated jenLama profile to not require  hidden prompt prefixes, etc.  Also removed all reins. She could be a bit too evil now.
- Various other changes
=> Make petals chats faster, update jenLama profile for compat.

src/lib/ChatRequest.svelte, src/lib/providers/petals/models.svelte, src/lib/providers/petals/request.svelte
- Fix some chat settings changes not being updated for completion requests without page refresh
- Fix WebSocket not being restarted after model change
- Change formatting of petals / Llama model requests for hopefully better/faster completions.
=> Bug fixes, Llama template changes

src/lib/ChatSettingsModal.svelte, src/lib/Settings.svelte, src/lib/providers/openai/models.svelte, src/lib/providers/petals/models.svelte, src/lib/providers/petals/request.svelte
- Fix bug with profile URL generation
- Some TypeScript issues.
- Default to StableBeluga2 since LLaMa-2 chat is often down.
=> Fix bug with profile URL generation

src/lib/EditMessage.svelte
Add button to copy message to clipboard re: #285
=> Add button to copy message to clipboard re: #285

README.md
* format the markdown
* structure a bit more some points
* add context for some others points
=> docs: :memo: improve (a bit) the documentation

src/lib/providers/openai/models.svelte
=> Add new model: GPT-4o-mini
