src/lib/Chat.svelte, src/lib/Types.svelte
Add a tooltip to each of the  chat settings. Tooltip content is the same as what is written for chat in the official documentation.
=> add tooltip to each of the chat settings, explaining what it does

.env, README.md, docker-compose.yml, mocked_api/Dockerfile-mockapi, mocked_api/mock_api.py, mocked_api/models_response.json
I found that waiting for the real API to respond can add up and consume a lot of time. This is especially true when testing UI and animations. 
This commit adds a mocked api that will just return some lorem ipsum text. Can customize how many seconds the response should load and how many sentences the response should be.
=> add mocked api to speed up development

src/app.scss, src/lib/Chat.svelte, src/lib/ChatMenuItem.svelte, src/lib/Profiles.svelte, src/lib/Settings.svelte, src/lib/Types.svelte
This adds:
- Short chat name suggestions.  Previously, depending on the content a name was being requested for, ChatGPT could return a much longer response than requested making the name so long you couldn't even get to the edit button.  This stops that.
- There's now a pencil icon on chat menu item hover to allow rename in place, similar to official ChatGPT.
- There's a new "Hidden Prompt Prefix" setting.  Any text entered there will be injected as a prefix to the last prompt in the request if it's a user prompt.  It will not be visible in chat, and will not be resent. One use case is to continually remind ChatGPT to stay character when responding.
=> Force short suggested names; rename from chat menu; hidden prompt prefix

src/lib/ChatRequest.svelte, src/lib/ChatSettingField.svelte, src/lib/ChatSettingsModal.svelte, src/lib/EditMessage.svelte, src/lib/Models.svelte, src/lib/Settings.svelte, src/lib/Stats.svelte, src/lib/Storage.svelte, src/lib/Types.svelte
- Sometimes GPT will send larger summaries than requested.  This adds a setting to allow that to be detected, and for the rest of the summary to be requested automatically.
- Token counts for requesting summarizations had a bug.
- Start refactoring model definitions, unifying them in one module with eventual goal to extend and add UI for custom models, hosts and endpoints.
=> Fixes for summarization, refactor model definitions.

package-lock.json, package.json, src/app.scss, src/lib/ApiUtil.svelte, src/lib/ChatCompletionResponse.svelte, src/lib/ChatRequest.svelte, src/lib/EditMessage.svelte, src/lib/Export.svelte, src/lib/ImageStore.svelte, src/lib/Models.svelte, src/lib/Settings.svelte, src/lib/Storage.svelte, src/lib/Types.svelte, src/lib/Util.svelte
- Added DALL-E images generation.  Once enabled, you can prompt: "show me an image of a monkey eating popcorn" and it will direct the prompt "a monkey eating popcorn" to the image generation endpoint.
- Added new gpt-3.5-turbo-16k and gpt-3.5-turbo-0613 models, per #171.  (token cost for base gpt-3.5-turbo model will need to be updated after the 27th.)
- Fixed textarea issues from #172
https://webifi.github.io/ChatGPT-Web-Updated-UI/
=> Add image generation, new gpt-3.5 models and fix #172

src/lib/Models.svelte
update token cost, add 0613 models for gpt-4
(Eventually I'll update the model request to pull down new gpt-3 and gpt-4 models automatically, though there doesn't seem to be anywhere to get updated pricing.)
=> update token cost, add 0613 models for gpt-4

src/lib/ChatOptionMenu.svelte, src/lib/EditMessage.svelte, src/lib/Sidebar.svelte
- Check the last few characters of the updated content for ``` and refresh the sveltemarkdown component to get code highlighting working #178
- Allow delete all chats menu option to work when not in a chat
=> Fix delete all chats option and code highlighting while streaming #178

src/lib/ChatSettingField.svelte, src/lib/ChatSettingsModal.svelte, src/lib/EditMessage.svelte
- When changing some setting in the chat settings dialog/modal, the scroll bar could jump around. This tries to fix that as much as possible.
- Use the faster includes instead of match when checking to update code highlighting.
=> Fix scroll jumping in settings dialog

src/lib/ChatRequest.svelte, src/lib/ChatSettingsModal.svelte, src/lib/Profiles.svelte
- Add option to the chat settings ... menu to apply the system prompt of the current settings to the current chat.
- Clarify that the "New Chat" options in the settings modal will create a new chat using the current settings.
- Fix a memory leak in how the abort handler was being used, and a bug in how it was implemented for aborting image generation requests.
=> Add "apply prompt" option, clarify the "new chat" buttons in settings, fix potential memory leak

src/lib/Chat.svelte, src/lib/ChatRequest.svelte, src/lib/EditMessage.svelte, src/lib/Messages.svelte, src/lib/Profiles.svelte, src/lib/Storage.svelte
- The larger chatStore got, the choppier streaming became, since it needed to save the entire chat store on every token received to display it in the message.  This update keeps a separate current messages cache for immediate message display/edits, then saves those changes to chatStore after activity has stopped for 100ms
- When switching between longer chat sessions, the UI would block and you wouldn't even see the chat change until the messages completed rendering.  Now the chat will change, show a loading indicator, then the UI will block until the messages render. (Not sure there's an easy way to get svelte to render long lists in a non-blocking way.)
=> Fix choppy streaming, mask UI blocking

src/lib/ChatRequest.svelte, src/lib/Storage.svelte
- Broke chat JSON restore while implementing smooth streaming/message cache.  Fixed.
- Summarization continuation wasn't working correctly.  Fixed.
- Increased message cache save inactivity threshold from 100ms to 200ms.
=> Fix restore chat JSON regression, Fix issue with summary continuation 

src/lib/ChatOptionMenu.svelte, src/lib/ChatRequest.svelte, src/lib/ChatSettingsModal.svelte, src/lib/Profiles.svelte, src/lib/Settings.svelte, src/lib/Util.svelte
- Added more expansion options for system prompt for hopefully more consistent output from character definitions. Expansions are ::EOM:: and ::START-PROMPT::
Say you have a system prompt of just:
```
You are an eager assistant. You are always happy to help.
```
This this is all that will be sent for your system prompt.
If your prompt is:
```
You are [[CHARACTER_NAME]], an eager assistant. You are always happy to help.
Example conversation follows:
::EOM::
Hey, can you please tell me what 2 + 2 is?
::EOM::
[[CHARACTER_NAME]]: Of course I can! 2 + 2 = 4!
::START-PROMPT::
Initial setting context:
[[CHARACTER_NAME]] sends a text asking how he can help.
```
Then what will be sent is a system prompt with:
```
You are Assistant Name, an eager assistant. You are always happy to help.
Example …
```
=> Adjustment to system prompt expansion, misc. UI tweaks

package-lock.json, package.json, src/lib/ApiUtil.svelte, src/lib/Chat.svelte, src/lib/ChatCompletionResponse.svelte, src/lib/ChatMenuItem.svelte, src/lib/ChatOptionMenu.svelte, src/lib/ChatRequest.svelte, src/lib/ChatRequestOpenAi.svelte, src/lib/ChatRequestPetals.svelte, src/lib/ChatSettingField.svelte, src/lib/ChatSettingsModal.svelte, src/lib/EditMessage.svelte, src/lib/Home.svelte, src/lib/Models.svelte, src/lib/Profiles.svelte, src/lib/Settings.svelte, src/lib/Sidebar.svelte, src/lib/Stats.svelte, src/lib/Storage.svelte, src/lib/Types.svelte, src/lib/Util.svelte
Adds experimental support for Llama 2 70b using Petals:
https://github.com/petals-infra/chat.petals.dev
Enable it on the home page.
The default endpoint for it should be overridden with your own Petals server.  The one included is only for testing.
=> Experimental support for Petals/Llama 2

src/lib/ChatRequestPetals.svelte, src/lib/Home.svelte, src/lib/Settings.svelte, src/lib/Types.svelte
Sometimes the stop sequence isn't detected by the host API and generation continues after it should have been stopped.  This adds an option that more aggressively looks for the stop sequence that may have passed through and drops the connection if it finds it.
=> Add an "Aggressive stop" sequence setting for Petals API calls

src/lib/ChatRequestPetals.svelte, src/lib/Models.svelte, src/lib/Settings.svelte, src/lib/Types.svelte
WebSocket connections were being left open for Petals API calls creating a new open connection for every request.  This is now fixed.
Llama-2-chat requests are new formatted to more closely follow what Meta trained it on:
https://huggingface.co/blog/llama2#how-to-prompt-llama-2
Also, this should be tested:
https://colab.research.google.com/drive/17Sn4AwrnHHN-lS1qoYltManEwgHOk-2d?usp=sharing
If it works out, it probably should be copied to GitHub and linked to in the webapp.
=> Close websocket connections, Format Llama-2-chat requests to Meta spec.

src/lib/ChatSettingsModal.svelte, src/lib/NewChat.svelte
- Fix issue where some profile settings pulled from url parameters were not applied.
- Add copy profile as URL to clipboard option. Allows sharing basic profile settings via url parameters.
=> Bugfix + add copy profile as URL to clipboard option

src/lib/providers/openai/models.svelte, src/lib/providers/openai/request.svelte
Added the following image generation models with prices:
DALL-E 3: 1024x1024, 1024x1792 (Portrait), 1792x1024 (Landscape).
Added DALL-E 3 options for the above sizes where quality=hd.
Added updated GPT-4 Turbo model: gpt-4-1106-preview
=> Added DALL-E models and gpt-4-1106-preview

src/lib/providers/openai/models.svelte, src/lib/providers/openai/request.svelte
From #445 
Added gpt-4-turbo-2024-04-09
Response's content-type changed to `content-type: text/event-stream; charset=utf-8`
=> Added gpt-4-turbo-2024-04-09

src/lib/Chat.svelte
Show what gpt model will be used for the current profile. 
The profile system is a very good idea but this annoyed me quite a lot. I think a lot of people might accidently end up using gpt-3.5 and not be aware of it. Now its clear what model will be used for the request.
=> Show gpt model in placeholder text

src/lib/Chat.svelte, src/lib/ChatRequest.svelte, src/lib/ChatSettingsModal.svelte, src/lib/Profiles.svelte, src/lib/Settings.svelte, src/lib/Types.svelte, src/lib/providers/openai/models.svelte, src/lib/providers/petals/request.svelte
Add o1 models and change `max_tokens `to `max_completion_tokens `since the former is now deprecated.
Streaming can't be enabled in profiles using these models.
Max Output tokens for these new models:
o1-preview: Up to 32,768 tokens
o1-mini: Up to 65,536 tokens
=> Add o1 Models
